force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Police_Verification__c.field-meta.xml
<CustomField>
    <fullName>Police_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Police Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchApplicant.cls
public class BatchApplicant implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchAbleContext Bc){
        return Database.getQueryLocator('select id , First_Name__c ,Gender__c ,Police_Verification__c  from Application__c where Gender__c =\'Male\' or Gender__c =\'Female\' ');
    }
    public void execute(Database.BatchAbleContext Bc ,List<Application__c> appList){
        if(!appList.isEmpty()){
            for(Application__c objapp:appList){
                if(objapp.Gender__c=='Male'){
                    objapp.Police_Verification__c=True;
                    
                }
                else{
                    if(objapp.Gender__c=='Female'){
                    objapp.Police_Verification__c=False;
                        
                    }
                }
            }
            Database.SaveResult[] result = Database.update(appList, false);
        
        }
        
    }
    public void finish(Database.BatchAbleContext Bc){
        
    }
}